// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notingham.API.DbContexts;

namespace Notingham.API.Migrations
{
    [DbContext(typeof(NotinghamContext))]
    [Migration("20200714024146_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Notingham.API.Entities.InvestmentManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InvestmentManagers");
                });

            modelBuilder.Entity("Notingham.API.Entities.InvestmentManagerStock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Cik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("InvestmentManagerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LinkToFinal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LinkToMain")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameOfIssuer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PeriodDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Shares")
                        .HasColumnType("int");

                    b.Property<string>("TickerCusip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TitleOfClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueOfShares")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("InvestmentManagerId");

                    b.ToTable("InvestmentManagerStocks");
                });

            modelBuilder.Entity("Notingham.API.Entities.InvestmentManagerStock", b =>
                {
                    b.HasOne("Notingham.API.Entities.InvestmentManager", "InvestmentManager")
                        .WithMany("investmentManagerStocks")
                        .HasForeignKey("InvestmentManagerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
